### ISSUE TITLE
Tabs für Tage

### ISSUE THREAD

**Issue by JensKriegerJuhnke** [evjukbu/festivalApp#8]
In der Eventsansicht sollte es Tabs für die unterschiedlichen Tage geben. 
Der "Boxed" Style in DaisyUI bietet sich an: https://daisyui.com/components/tab/

**Comment by theCVDH** [comment]
![Frame 18](https://github.com/evjukbu/festivalApp/assets/7714178/9f35e247-fef0-48dc-8a1c-73a472e5a892)

**Comment by JensKriegerJuhnke** [comment]
(Außer die Seitenleiste mit dem "progress") Done.
